### ISSUE TITLE
[Android][Google Sign In] accounts.notifySocialLogin fail on 5.1.2

### ISSUE THREAD

**Issue by volodia-chornenkyi-discovery** [SAP/gigya-android-sdk#24] opened 2021-06-07 13:32 UTC
During the sign in flow on Android via Google we get the following error:
`{  "callId": "736b3ed5f15c48a193969c53df22c373",  "errorCode": 500002,  "errorMessage": "Server login error",  "apiVersion": 2,  "statusCode": 500,  "statusReason": "Internal Server Error",  "time": "2021-06-07T10:59:24.828Z",  "errorDetails": "500002 - Server login error"}`

After debugging the library it happens during a call to `accounts.notifySocialLogin` with auth code received from the Google Sign-In SDK.

**Comment by tal-mi** [comment] 2021-06-07 13:57
Can you please elaborate on the "sign-in flow" you are performing?
Is it a simple social login request? interruption resolving? 

I will check this error and update this thread.

Thanks,

Tal

**Comment by volodia-chornenkyi-discovery** [comment] 2021-06-07 14:22
Hi @tal-mi, yes, general social sign-in via Google for the existing user but on the newer SDK (previously we had v3.x and it works there).

Gigya#login()
socialProvider = google
conflictHandling = fail

**Comment by tal-mi** [comment] 2021-06-07 14:29
Thanks.
I passed this specific error for further investigation.
I Will update as soon as I find something.

**Comment by tal-mi** [comment] 2021-06-08 07:03
Hi,

Seems that Google failed to authenticate the code sent via "notifySocialLogin".
This is usually caused when Google sign-in is not configured correctly.
I assume you followed these steps:
https://sap.github.io/gigya-android-sdk/sdk-core/#google

Please make sure that you add the web client id (oauth2) in the manifest.xml meta-data. 

If the issue persists please open a [support ticket](https://developers.gigya.com/display/GD/Opening+A+Support+Incident) and we will be able to resolve this online.

**Comment by volodia-chornenkyi-discovery** [comment] 2021-06-08 12:46
Hi @tal-mi, Google sign-in setup was done according to the steps from [https://sap.github.io/gigya-android-sdk/sdk-core/#google](https://sap.github.io/gigya-android-sdk/sdk-core/#google) and web client id is in the AndroidManifest.xml.

Could you provide more info about the redirect URIs? Is it critical to have https://socialize.<DataCenter>/GS/GSLogin.aspx? added? I was able to find this info only for Site Setup and nothing on Mobile pages: https://help.sap.com/viewer/8b8d6fffe113457094a17701f63e3d6a/LATEST/en-US/415ba6c470b21014bbc5a10ce4041860.html

**Comment by tal-mi** [comment] 2021-06-08 12:51
Hi,

Yes, it is required to add the following redirect URIs. According to the data center used.
If it is not explained well in the documentation I will make sure to add it accordingly.

**Comment by volodia-chornenkyi-discovery** [comment] 2021-06-08 13:41
Yeah, this would be really helpful for other devs to add at least a reference to the Site Setup page. Hopefully, it will resolve our issue.

**Comment by tal-mi** [comment] 2021-06-08 14:00
Please update if the issue was resolved.

Thanks,
Tal

**Comment by galunecandrey** [comment] 2021-06-10 12:47
@tal-mi I have the same issue. SDK try send request {'google':{'code': 'serverAuthCode'}} and it doesnt work.
But when I try send {'google':{'authToken': 'authentication.accessToken'}}  its work.

**Comment by tal-mi** [comment] 2021-06-10 12:51
I will take this with our backend team to verify if {'google':{'authToken': 'authentication.accessToken'}} is an approved method.
Currently, it is not recommended as the designed flow is using  {'google':{'code': 'serverAuthCode'}}  after the Google sign-in setup is done correctly.

**Comment by volodia-chornenkyi-discovery** [comment] 2021-06-15 13:04
@tal-mi any updates from the backend team&

**Comment by tal-mi** [comment] 2021-06-15 21:01
I have escalated this and will update once I have something.
Do you still have issues connecting to Google after setting the redirect URIs?

**Comment by volodia-chornenkyi-discovery** [comment] 2021-06-16 15:45
Yes, the issue still persists with added redirect URIs to the web OAuth client.

`{  "callId": "f90464702c30498aafb782eeaa2325c0",  "errorCode": 500002,  "errorMessage": "Server login error",  "apiVersion": 2,  "statusCode": 500,  "statusReason": "Internal Server Error",  "time": "2021-06-16T15:44:23.259Z",  "errorDetails": "500002 - Server login error"}`

**Comment by tal-mi** [comment] 2021-06-16 16:34
I have attached a video I just recorded on how to implement Google Sign In via the latest SDK on a clear project.

https://user-images.githubusercontent.com/47209216/122258498-c4358900-ced9-11eb-84f1-b5c758fd87f8.mov

**Comment by galunecandrey** [comment] 2021-06-16 17:03
I did everything as shown in the video but:
```
{callId: 2b63aa57d0ce42058cffd6b382168ef8, errorMessage: Server login error, time: 2021-06-16T16:56:56.083Z, statusCode: 500, statusReason: Internal Server Error, errorDetails: 500002 - Server login error, apiVersion: 2, errorCode: 500002}
```

**Comment by tal-mi** [comment] 2021-06-16 17:04
What datacenter are you using for your site?

**Comment by galunecandrey** [comment] 2021-06-16 17:06
us1

**Comment by tal-mi** [comment] 2021-06-16 17:09
I will check with our backend team and update.
Need to determine the cause of this error.

**Comment by tal-mi** [comment] 2021-07-01 09:49
Further investigation of the callID provided suggested that there is a problem with the redirect URIs.
This would suggest an implementation issue.

Please open a support case via SAP standard support. https://developers.gigya.com/display/GD/Opening+A+Support+Incident

And we will be able to continue investigating this further.

**Comment by tal-mi** [comment] 2021-08-30 10:10
Are you still experiencing this issue?

**Comment by galunecandrey** [comment] 2021-08-30 10:36
@tal-mi yes

**Comment by tal-mi** [comment] 2021-08-30 11:16
Please open a support case via:
https://developers.gigya.com/display/GD/Opening+A+Support+Incident
We might need an online session in order to clarify the issue.

Tal.

**Closed** 2022-01-27 10:02 UTC

**Comment by skyphantomhz** [comment] 2023-06-05 10:31
Hi,
I have same issue. Please correct me which should use `{'google':{'authToken': 'authentication.accessToken'}}` or `{'google':{'authToken': 'authentication.accessToken'}}`

**Comment by tal-mi** [comment] 2023-06-05 22:05
"providerSessions" object should use "code" for Google not authToken. You should not send the code as a parameter as well.

**Comment by skyphantomhz** [comment] 2023-06-06 02:27
After update the request, i got this error

<img width="1103" alt="Screen Shot 2023-06-06 at 09 19 31" src="https://github.com/SAP/gigya-android-sdk/assets/19892362/3e4120d0-df6f-4019-9a99-661c7410bc3f">

The iOS guys can login with google properly. The difference is they use `googleplus` instead `google` on `providerSessions`. I try to change to `googleplus` but the error still happen.
